# DO NOT EDIT. This file was auto generated by ../scripts/generate-pkg.sh
{ pkgs ? import <nixpkgs> { } }:

pkgs.stdenv.mkDerivation {
  name = "fetch-hls";
  src = pkgs.fetchurl {
    url = "https://github.com/dustinblackman/fetch-hls/releases/download/v0.1.5/fetch-hls_0.1.5_linux_arm64.tar.gz";
    sha256 = "17w9n3alvsa29nlp4xrqyaqa537xpswmdkhcfxvs3qii0dh8lwxs";
  };
  phases = [ "installPhase" ];
  installPhase = ''
    mkdir -p $out/bin
    tar -zxvf $src -C $out/bin/ fetch-hls
  '';
}

