# DO NOT EDIT. This file was auto generated by ../scripts/generate-pkg.sh
{ pkgs ? import <nixpkgs> { } }:

pkgs.stdenv.mkDerivation {
  name = "languagetool-code-comments";
  src = pkgs.fetchurl {
    url = "https://github.com/dustinblackman/languagetool-code-comments/releases/download/v0.4.3/languagetool-code-comments_0.4.3_linux_amd64.tar.gz";
    sha256 = "15n5iaj23ykg58lxglhqfplv205hxcjdgrf8yanqasslwcqfp9hd";
  };
  phases = [ "installPhase" ];
  installPhase = ''
    mkdir -p $out/bin
    tar -zxf $src -C $out/bin/ languagetool-code-comments
  '';
}

