# DO NOT EDIT. This file was auto generated by ../scripts/generate-pkg.sh
{ pkgs ? import <nixpkgs> { } }:

pkgs.stdenv.mkDerivation {
  name = "oatmeal";
  src = pkgs.fetchurl {
    url = "https://github.com/dustinblackman/oatmeal/releases/download/v0.2.2/oatmeal_0.2.2_linux_amd64.tar.gz";
    sha256 = "1r8h3bm5z67kyrjlrzrljs3vm282mx3vcsn9ss17m6v3zm8k69pk";
  };
  phases = [ "installPhase" ];
  installPhase = ''
    mkdir -p $out/bin
    tar -zxf $src -C $out/bin/ oatmeal
  '';
}

